### ISSUE TITLE
Addition to the plugin.

### ISSUE THREAD

**Issue by SargonofAssyria** [vaneeten/domoticz-wudirect#11]
In Domoticz are a few combined devices, which split up in 2 devices with the same caption in 2 tabs.
I have added 2 devices to be able to have different captions.
THB device added TH for just only temperature and humidity in 1 device. Barometer has his own device.
WTC device added Wind device for just wind without temperature and humidity.
Perhaps you could include those.
`    'TH'        : {
        'nr'    : 105,
        'type'  : "Temp+Hum",
        'src'   : ['tempf','humidity','_humstat,humidity,tempf']
    },
    'Wind'      : {
        'nr'    : 106,
        'type'  : "Wind",
        'src'   : ['winddir','_winddir,winddir','_windms10,windspeedmph','_windms10,windgustmph','tempf','windchillf$
    }
`

**Comment by vaneeten** [comment]
It is unlikely for me to add new functionality to WuDirect as I am not using it anymore.
