### ISSUE TITLE
(FindModule) Domoticz/DomoticzEx modules not found in interpreter.

### ISSUE THREAD

**Issue by mcmellow** [vaneeten/domoticz-wudirect#5]
See enclosed log:

```
2021-11-18 12:09:08.002 Status: PWS: Stop directive received.
2021-11-18 12:09:08.424 Status: PWS: Exiting work loop.
2021-11-18 12:09:08.507 Status: PWS: Stopping threads.
2021-11-18 12:09:08.508 Status: PWS: Stopped.
2021-11-18 12:09:08.348 Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter.
2021-11-18 12:09:08.348 Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter.
2021-11-18 12:09:45.202 Status: PWS: Started.
2021-11-18 12:09:45.202 Status: PWS: Entering work loop.
2021-11-18 12:09:45.423 Status: PWS: Initialized version 0.2.2, author 'mveeten'
```
After updating or stopping/starting the WUDirect hardware in Domoticz  This error FindModule appears.

Domoticz is at build 13872

**Comment by vaneeten** [comment]
A quick google suggests that your error message is caused by a new Python plugin framework that is currently being developed and thus available in your _Beta_ version of Domoticz. Do you also encounter this problem with the current _Stable_ version of Domoticz?

**Comment by Eddie-BS** [comment]
I am running the same version and do not see this message

**Comment by mcmellow** [comment]
> A quick google suggests that your error message is caused by a new Python plugin framework that is currently being developed and thus available in your _Beta_ version of Domoticz. Do you also encounter this problem with the current _Stable_ version of Domoticz?

I have no other versions of Domoticz  running.  I had  Data Timeout set to 10 min and every restart this  (FindModule) error.  I don't know or this has any affect on the working of the WuDirect plugin. 

It seems my PWS console is not sending any data to a customized server, so I don't know about the plugin is working OK.

**Comment by Eddie-BS** [comment]
@mcmellow did you change the <server> on your PWS ?
in that case, there is no data send to WU anymore ...
If you intercept the data on your router (like I do) and send it to a "splitter" webinstance,
that webinstance sends the data to WU and to the WuDirect pluging ...
In that case you can easily see the data from yout pws in the logging of the webinstance

**Comment by mcmellow** [comment]
This is another approach. 
I tried WU first and filled in a station ID / password at the WU screen in WS View. Just to see or any data is passing my router. 
Then I deleted the WU station ID / Password from the WU screen and filled in the Domoticz IP address in the customized screen. But no data is received by Domoticz. That is the status at this moment.

I have no clue how to split data on my router (KPN Experia V10 box) and send it to WU and my local Domoticz

**Comment by Eddie-BS** [comment]
intercepting on an experia is rather impossible ...
the splitting can be done easy but is of no use if you do not split ...
please double check the IP and PORT on the PWS, it should be the IP of your domoticz machine and the PORT you configured in the plugin-config
<img width="297" alt="Screenshot 2021-11-18 at 16 05 55" src="https://user-images.githubusercontent.com/10174704/142441107-5acd6e3e-e119-4beb-92a5-d76d7883bf94.png">
So my PWS sends data to the IP of my domoticz and port 8008 ...

**Comment by mcmellow** [comment]
Thanks, that is exact what I would like to do.  That's is als what I have filled in at The WuDirect hardware. But I am afraid my problem is at the PWS side, by not sending any data that is configured in the customized screen of WS-View

**Comment by mcmellow** [comment]
Id did the following test to see or the customized section is working OK.
First send the data WU setup with the WU screen. Just Station ID and Station key.  This worked well, at wunderground was updated every 20 sec or so.

Second configured the WU station at the customized screen with the following data
**Enable
Protocol Type Same As: Wunderground
Server IP / Hostname: weatherstation.wunderground.com
Path: /weatherstation/updateweatherstation.php?
Station ID:  IHARDE61
Station key: MyStationKey
Port: 80
Upload interval: 30**

They amazing thing is my WU station is updated about every 30 sec.   Why does it works with the WU credentials and not with my Domoticz credentials or the www.pwsweather.com credentials.?  Do we need to fill in something in path, station ID and station key aswell? And if yes what?

**Comment by vaneeten** [comment]
I'm not sure I understand what you're trying, but WS View should allow you to configure a **Custom** output. On this Custom WS View settings page, only a few things are relevant: the protocol switch, which must be Wunderground, and "Server IP / Hostname", which must be set to the IP address of your Domoticz server, and "Port" which must correspond to the port number you configured for the WuDirect plugin. Path can be anything as long as it starts with a "/" and ends with a "?", and "Station ID" and password can also be anything - they are not used in WuDirect at all. WuDirect only parses the Wunderground data which your PWS should transmit as part of the URL after the question mark.

**Comment by mcmellow** [comment]
Finally, I have got it working by send data to Domoticz and WuDirect. Don't know why, but it works. 
It might be possible something odd on my PWS Console.  Filled in for Path: /?  The Domoticz Hardware name for the Station ID and for Station key 123. 
Thanks for all the support. This issue can be closed.
