### ISSUE TITLE
baro value drops to 0 a couple of times per day

### ISSUE THREAD

**Issue by Eddie-BS** [vaneeten/domoticz-wudirect#6]
Hi,

the value of  baro drops to 0 (zero) a couple of times per day, causes the graph to be wrong ...
I recall you added a min and max on baro to prevent this but it seems not to work.
Is it possible to modify the code to ignore a value like this and NOT write it to the database  ?
<img width="536" alt="Screenshot 2021-11-22 at 20 19 34" src="https://user-images.githubusercontent.com/10174704/142922438-36a90905-07af-423b-8c0c-835794a61715.png">
>
the bottom line is 0 (zero)

**Comment by vaneeten** [comment]
That's really weird. What is the Unit number of the Barometer device that gives you zeros - or are both affected?

**Comment by Eddie-BS** [comment]
<img width="844" alt="Screenshot 2021-11-23 at 07 41 12" src="https://user-images.githubusercontent.com/10174704/142980669-ea1106b1-db7b-42bc-8761-f3eeb5f83a0e.png">

For now it seems only Barometer (102) 
Combined sensor THB (100) is effected to. 
Pressure (6) looks not affected ...

**Comment by Eddie-BS** [comment]
this morning ...
<img width="397" alt="Screenshot 2021-11-24 at 10 08 17" src="https://user-images.githubusercontent.com/10174704/143208094-6b588232-9599-4f80-9fd3-4fffbaf6d440.png">

that value of NULL is appearently not entered into the database ...

<img width="1173" alt="Screenshot 2021-11-24 at 10 14 22" src="https://user-images.githubusercontent.com/10174704/143209196-a51a6cdb-8b04-4e73-8b11-34de66f9a70e.png">

**Comment by vaneeten** [comment]
Hi Eddie, if you know how to get files from the **testing** branch then you can already try it out: it contains a patch for this problem. Thus far it works for me, and if it still works tomorrow then I'll merge it into the **master** branch.

**Comment by Eddie-BS** [comment]
Hi, 
I will wait for the official release this time, rather busy today

**Comment by Eddie-BS** [comment]
Hi, 
I just installed the latest version, I will let you know in a couple of days if this solves the problem.

did you consider to contact stas-demydiuk to incorperate WuDirect in the plugins-manager  ?
https://github.com/stas-demydiuk/domoticz-plugins-manager/tree/master
you should get a lot more exposure ;-)

**Comment by vaneeten** [comment]
Patch has been merged into master branch. And @Eddie-BS , thank you for your support for WuDirect! Somehow the Domoticz forum doesn't send me any notifications...

**Comment by Eddie-BS** [comment]
Are you subscribed to  the forum topic ?
If so, look in you spambox and whitelist the sender domain

Eddie

**Comment by vaneeten** [comment]
Just to be sure, I checked all the email boxes in the Domoticz forum, and now I'm receiving something.
I also requested inclusion into the Python Plugins Manager - the benefits of a rainy day :-)

**Comment by Eddie-BS** [comment]
Great work, 

notifications on subscribed topic is really nice !

btw, I noticed a crash in the plugin after enabling / disabling the loglevel info switch …
